### ISSUE TITLE
缺少模型

### ISSUE THREAD

**Issue by kintong3000** [chaodreaming/free-translate-api#1]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/85821314/227127420-025121a7-dbe2-4fc1-9759-76336f9e77d9.png">

**Comment by chaodreaming** [comment]
这显然是正常的，因为还没有写完，等整理好模型之后会增加自动下载功能，现在还是不可用的，请耐心等待

**Comment by kintong3000** [comment]
> 这显然是正常的，因为还没有写完，等整理好模型之后会增加自动下载功能，现在还是不可用的，请耐心等待

我以为做好上线了
请教一下，我有一个数据集，大概有几亿个字符，有没有办法免费翻译，可以拆分，但是我拆分后去翻译还是说我字符过多，有没有方便的方法

**Comment by chaodreaming** [comment]
这个模型本质上也只是支持128token，翻译速度大概200ms左右，因为支持批量翻译，有一张差不多的卡的话，一天理想情况可以翻译上亿字符的，本质还是拆分翻译

**Comment by kintong3000** [comment]
> 这个模型本质上也只是支持128token，翻译速度大概200ms左右，因为支持批量翻译，有一张差不多的卡的话，一天理想情况可以翻译上亿字符的，本质还是拆分翻译

老板叫我解决这个问题，我好急，它又不肯花钱用api 😂

**Comment by chaodreaming** [comment]
翻译效果可以，但是做不到商业程度，上亿字符商业也要几千块起步了，这几天就会整理好了

**Comment by kintong3000** [comment]
> 翻译效果可以，但是做不到商业程度，上亿字符商业也要几千块起步了，这几天就会整理好了

大概准确就可以了，数据集用来跑模型的，老板只会提要求，吗的，要我一个实习生去写transformer翻译模型，我东拼西凑几天弄了一个，但是好像数据集太小了，效果不好，但起码能出结果。老板什么都不懂天天在催。

**Comment by chaodreaming** [comment]
模型可以自动下载了

**Comment by kintong3000** [comment]
> 模型可以自动下载了

感谢
